[package]
name = "Jetson_Robot_Rust"
version = "0.1.0"
authors = ["Josh <JKI757@joshki.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
